version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    exclude-paths:
      - "requirements.txt"
      - "requirements-min.txt"
      - "requirements-all.txt"
      - "requirements-dev.txt"
