version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    exclude-paths:
      - "requirements.txt"
      - "requirements-min.txt"
      - "requirements-all.txt"
      - "requirements-dev.txt"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
