---
APPLY_FIXES: all

PRE_COMMANDS:
  - command: apk add py3-numpy
    cwd: "workspace"   # Will be run at the root of the workspace (usually your repository root)
    continue_if_failed: False  # Will stop the process if command is failed (return code > 0)

DISABLE_LINTERS:
  - SPELL_CSPELL
  - PYTHON_PYRIGHT
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRIVY # Reenable as soon as (if?) https://avd.aquasec.com/nvd/2021/cve-2021-29063/ confirms that 1.3.0 is no longer a risk
  - JSON_JSONLINT # Disable because there is only .devcontainer.json, for which it throws an unwanted warning
