from .abstract_cart_prod_distribution import AbstractCartProdDistribution
from ..abstract_dirac_distribution import AbstractDiracDistribution

class CartProdDiracDistribution(AbstractDiracDistribution, AbstractCartProdDistribution):
    pass
