"""Utility helpers for :mod:`pyrecest`."""

from .assignment import murty_k_best_assignments
from .association_features import (
    CalibratedPairwiseAssociationModel,
    NamedPairwiseFeatureSchema,
    pairwise_feature_tensor,
)
from .association_models import LogisticPairwiseAssociationModel
from .history_recorder import HistoryRecorder
from .metrics import (
    anees,
    anis,
    chi_square_confidence_bounds,
    chi_square_confidence_interval,
    consistency_fraction,
    eot_shape_iou,
    extent_error,
    extent_intersection_over_union,
    extent_matrix_error,
    extent_wasserstein_distance,
    gaussian_wasserstein_distance,
    gospa_distance,
    iou_polygon,
    is_chi_square_consistent,
    is_within_chi_square_confidence_interval,
    mae,
    mospa_distance,
    mse,
    nees,
    nees_confidence_bounds,
    nees_confidence_interval,
    nis,
    nis_confidence_bounds,
    nis_confidence_interval,
    ospa_distance,
    rmse,
)
from .multisession_assignment import (
    MultiSessionAssignmentResult,
    solve_multisession_assignment,
    tracks_to_session_labels,
)
from .multisession_assignment_observation_costs import (
    solve_multisession_assignment_with_observation_costs,
)
from .multisession_assignment_score import (
    solve_multisession_assignment_from_similarity,
    stitch_tracks_from_pairwise_scores,
    tracks_to_index_matrix,
)
from .nonrigid_point_set_registration import (
    ThinPlateSplineRegistrationResult,
    ThinPlateSplineTransform,
    estimate_thin_plate_spline,
    joint_tps_registration_assignment,
)
from .pairwise_covariance_features import (
    pairwise_covariance_shape_components,
    pairwise_mahalanobis_distances,
)
from .track_evaluation import (
    complete_track_set,
    normalize_track_matrix,
    pairwise_track_set,
    reference_fragment_counts,
    score_complete_tracks,
    score_false_continuations,
    score_fragmentation,
    score_pairwise_tracks,
    score_track_fragmentation,
    score_track_links,
    score_track_matrices,
    summarize_track_errors,
    summarize_tracks,
    track_error_ledger,
    track_lengths,
    track_pair_set,
)
from .track_metrics import (
    false_track_rate,
    missed_track_rate,
    score_false_tracks,
    score_missed_tracks,
    score_track_latency,
    score_track_outcomes,
    score_track_purity,
    track_latencies,
    track_purity,
)

__all__ = [
    "MultiSessionAssignmentResult",
    "solve_multisession_assignment",
    "solve_multisession_assignment_from_similarity",
    "solve_multisession_assignment_with_observation_costs",
    "stitch_tracks_from_pairwise_scores",
    "tracks_to_index_matrix",
    "tracks_to_session_labels",
    "anis",
    "anees",
    "chi_square_confidence_bounds",
    "chi_square_confidence_interval",
    "consistency_fraction",
    "eot_shape_iou",
    "extent_error",
    "extent_intersection_over_union",
    "extent_matrix_error",
    "extent_wasserstein_distance",
    "false_track_rate",
    "gaussian_wasserstein_distance",
    "gospa_distance",
    "iou_polygon",
    "is_chi_square_consistent",
    "is_within_chi_square_confidence_interval",
    "mae",
    "missed_track_rate",
    "mospa_distance",
    "mse",
    "nees",
    "nees_confidence_bounds",
    "nees_confidence_interval",
    "nis",
    "nis_confidence_bounds",
    "nis_confidence_interval",
    "ospa_distance",
    "rmse",
    "score_false_tracks",
    "score_missed_tracks",
    "score_track_latency",
    "score_track_outcomes",
    "score_track_purity",
    "track_latencies",
    "track_purity",
    "CalibratedPairwiseAssociationModel",
    "LogisticPairwiseAssociationModel",
    "NamedPairwiseFeatureSchema",
    "pairwise_feature_tensor",
    "HistoryRecorder",
    "ThinPlateSplineRegistrationResult",
    "ThinPlateSplineTransform",
    "estimate_thin_plate_spline",
    "joint_tps_registration_assignment",
    "murty_k_best_assignments",
    "pairwise_covariance_shape_components",
    "pairwise_mahalanobis_distances",
    "complete_track_set",
    "normalize_track_matrix",
    "pairwise_track_set",
    "reference_fragment_counts",
    "score_complete_tracks",
    "score_false_continuations",
    "score_fragmentation",
    "score_pairwise_tracks",
    "score_track_fragmentation",
    "score_track_links",
    "score_track_matrices",
    "summarize_track_errors",
    "summarize_tracks",
    "track_error_ledger",
    "track_lengths",
    "track_pair_set",
]
