# pylint: disable=no-name-in-module,no-member,duplicate-code
"""Exact multi-Bernoulli-mixture tracker for linear/Gaussian models.

The existing :class:`MultiBernoulliTracker` is kept as the lightweight
single-posterior nearest-neighbor approximation.  This module adds an explicit
nearest-neighbor alias and a separate tracker that preserves the exact
multi-Bernoulli mixture generated by the measurement update.
"""

import copy
from math import exp, log

# pylint: disable=no-name-in-module,no-member
from pyrecest.backend import argmax, array, empty, ndim, stack
from scipy.special import logsumexp

from .multi_bernoulli_tracker import MultiBernoulliTracker

# Explicit name for the existing single-posterior, best-assignment tracker.
NearestNeighborMultiBernoulliTracker = MultiBernoulliTracker


class MultiBernoulliMixtureHypothesis:
    """A global hypothesis in a multi-Bernoulli mixture posterior."""

    def __init__(self, weight, bernoulli_components):
        if float(weight) < 0.0:
            raise ValueError("Global hypothesis weights must be nonnegative.")
        self.weight = float(weight)
        self.bernoulli_components = MultiBernoulliTracker._normalize_components(
            bernoulli_components
        )

    def get_cardinality_distribution(self):
        cardinality_pmf = [1.0]
        for component in self.bernoulli_components:
            existence_probability = float(component.existence_probability)
            new_cardinality_pmf = [0.0] * (len(cardinality_pmf) + 1)
            for cardinality, probability in enumerate(cardinality_pmf):
                new_cardinality_pmf[cardinality] += (
                    1.0 - existence_probability
                ) * probability
                new_cardinality_pmf[cardinality + 1] += (
                    existence_probability * probability
                )
            cardinality_pmf = new_cardinality_pmf
        return array(cardinality_pmf)

    def get_expected_number_of_targets(self):
        return sum(
            component.existence_probability for component in self.bernoulli_components
        )


class MultiBernoulliMixtureTracker(MultiBernoulliTracker):
    """Exact MBM tracker for linear/Gaussian multi-Bernoulli updates.

    A multi-Bernoulli prior is not closed under the standard measurement update
    with detection uncertainty and clutter; the exact posterior is a mixture of
    multi-Bernoulli densities over global association hypotheses.  This tracker
    keeps those hypotheses instead of collapsing them to the best association.
    """

    DEFAULT_TRACKER_PARAM = {
        **MultiBernoulliTracker.DEFAULT_TRACKER_PARAM,
        "hypothesis_pruning_threshold": 1e-12,
        "maximum_number_of_hypotheses": None,
        "measurement_driven_births": False,
    }

    def __init__(
        self,
        initial_prior=None,
        tracker_param=None,
        birth_components=None,
        log_prior_estimates=True,
        log_posterior_estimates=True,
    ):
        super().__init__(
            initial_prior=None,
            tracker_param=tracker_param,
            birth_components=birth_components,
            log_prior_estimates=log_prior_estimates,
            log_posterior_estimates=log_posterior_estimates,
        )
        self.hypotheses = [MultiBernoulliMixtureHypothesis(1.0, [])]
        if initial_prior is not None:
            self.filter_state = initial_prior
        else:
            self._sync_map_components()

    @property
    def filter_state(self):
        return copy.deepcopy(self.hypotheses)

    @filter_state.setter
    def filter_state(self, new_state):
        if isinstance(new_state, MultiBernoulliMixtureHypothesis):
            hypotheses = [copy.deepcopy(new_state)]
        else:
            state_items = list(new_state)
            if state_items and all(
                isinstance(item, MultiBernoulliMixtureHypothesis)
                for item in state_items
            ):
                hypotheses = copy.deepcopy(state_items)
            else:
                hypotheses = [MultiBernoulliMixtureHypothesis(1.0, state_items)]
        self._set_hypotheses(hypotheses)
        if self.log_prior_estimates:
            self.store_prior_estimates()

    def _set_hypotheses(self, hypotheses):
        self.hypotheses = hypotheses or [MultiBernoulliMixtureHypothesis(1.0, [])]
        self._normalize_hypothesis_weights()
        for hypothesis in self.hypotheses:
            self._assign_missing_labels(hypothesis.bernoulli_components)
        self._sync_map_components()

    def _normalize_hypothesis_weights(self):
        total_weight = sum(hypothesis.weight for hypothesis in self.hypotheses)
        if total_weight <= 0.0:
            raise ValueError(
                "At least one global hypothesis must have positive weight."
            )
        for hypothesis in self.hypotheses:
            hypothesis.weight = float(hypothesis.weight) / total_weight

    def _sync_map_components(self):
        if not self.hypotheses:
            self.bernoulli_components = []
            return
        self.bernoulli_components = copy.deepcopy(
            self.get_map_hypothesis(copy_hypothesis=False).bernoulli_components
        )

    def get_map_hypothesis(self, copy_hypothesis=True):
        if not self.hypotheses:
            raise ValueError("No global hypotheses are available.")
        hypothesis = max(self.hypotheses, key=lambda item: item.weight)
        return copy.deepcopy(hypothesis) if copy_hypothesis else hypothesis

    def get_mixture_weights(self):
        return array([hypothesis.weight for hypothesis in self.hypotheses])

    def get_component_labels(self):
        labels = []
        seen_labels = set()
        for hypothesis in sorted(
            self.hypotheses,
            key=lambda item: item.weight,
            reverse=True,
        ):
            for component in hypothesis.bernoulli_components:
                if component.label not in seen_labels:
                    labels.append(copy.deepcopy(component.label))
                    seen_labels.add(component.label)
        return labels

    def get_number_of_components(self):
        return len(self.get_component_labels())

    def get_existence_probabilities(self):
        labels = self.get_component_labels()
        existence_probabilities = []
        for label in labels:
            existence_probability = 0.0
            for hypothesis in self.hypotheses:
                for component in hypothesis.bernoulli_components:
                    if component.label == label:
                        existence_probability += (
                            hypothesis.weight * component.existence_probability
                        )
                        break
            existence_probabilities.append(existence_probability)
        return array(existence_probabilities)

    def get_cardinality_distribution(self):
        if not self.hypotheses:
            return array([1.0])
        max_cardinality = max(
            len(hypothesis.bernoulli_components) for hypothesis in self.hypotheses
        )
        cardinality_pmf = [0.0] * (max_cardinality + 1)
        for hypothesis in self.hypotheses:
            hypothesis_cardinality_pmf = hypothesis.get_cardinality_distribution()
            for cardinality, probability in enumerate(hypothesis_cardinality_pmf):
                cardinality_pmf[cardinality] += hypothesis.weight * probability
        return array(cardinality_pmf)

    def get_expected_number_of_targets(self):
        return sum(
            hypothesis.weight * hypothesis.get_expected_number_of_targets()
            for hypothesis in self.hypotheses
        )

    def get_number_of_targets(self):
        return int(argmax(self.get_cardinality_distribution()))

    def get_labeled_components(self, copy_components=True):
        components = self.get_map_hypothesis(copy_hypothesis=False).bernoulli_components
        return {
            copy.deepcopy(component.label): (
                copy.deepcopy(component) if copy_components else component
            )
            for component in components
        }

    def get_component_by_label(self, label, copy_component=True):
        for component in self.get_map_hypothesis(
            copy_hypothesis=False
        ).bernoulli_components:
            if component.label == label:
                return copy.deepcopy(component) if copy_component else component
        raise KeyError(f"No Bernoulli component with label {label!r} exists.")

    def get_labeled_point_estimate(self, flatten_vector=False, number_of_targets=None):
        map_components = self.get_map_hypothesis(
            copy_hypothesis=False
        ).bernoulli_components
        if not map_components:
            point_estimates = array([]) if flatten_vector else empty((0, 0))
            return [], point_estimates
        if number_of_targets is None:
            number_of_targets = self.get_number_of_targets()
        if number_of_targets <= 0:
            point_estimates = empty((map_components[0].dim, 0))
            labels = []
        else:
            selected_components = sorted(
                map_components,
                key=lambda component: component.existence_probability,
                reverse=True,
            )[:number_of_targets]
            labels = [
                copy.deepcopy(component.label) for component in selected_components
            ]
            point_estimates = stack(
                [component.get_point_estimate() for component in selected_components],
                axis=1,
            )
        if flatten_vector:
            point_estimates = point_estimates.flatten()
        return labels, point_estimates

    def prune(self, pruning_threshold=None):
        if pruning_threshold is None:
            pruning_threshold = self.tracker_param["pruning_threshold"]
        for hypothesis in self.hypotheses:
            hypothesis.bernoulli_components = [
                component
                for component in hypothesis.bernoulli_components
                if component.existence_probability >= pruning_threshold
            ]
        hypothesis_threshold = self.tracker_param.get(
            "hypothesis_pruning_threshold",
            1e-12,
        )
        retained_hypotheses = [
            hypothesis
            for hypothesis in self.hypotheses
            if hypothesis.weight >= hypothesis_threshold
        ]
        if not retained_hypotheses and self.hypotheses:
            retained_hypotheses = [self.get_map_hypothesis(copy_hypothesis=True)]
        self.hypotheses = retained_hypotheses
        self._normalize_hypothesis_weights()
        self._sync_map_components()

    def cap(self, maximum_number_of_components=None):
        if maximum_number_of_components is None:
            maximum_number_of_components = self.tracker_param[
                "maximum_number_of_components"
            ]
        if maximum_number_of_components is not None:
            for hypothesis in self.hypotheses:
                hypothesis.bernoulli_components = sorted(
                    hypothesis.bernoulli_components,
                    key=lambda component: component.existence_probability,
                    reverse=True,
                )[:maximum_number_of_components]
        maximum_number_of_hypotheses = self.tracker_param.get(
            "maximum_number_of_hypotheses",
            None,
        )
        if maximum_number_of_hypotheses is not None:
            self.hypotheses = sorted(
                self.hypotheses,
                key=lambda hypothesis: hypothesis.weight,
                reverse=True,
            )[:maximum_number_of_hypotheses]
            self._normalize_hypothesis_weights()
        self._sync_map_components()

    def predict_linear(
        self, system_matrices, sys_noises, inputs=None, birth_components=None
    ):
        sys_noises = self._coerce_zero_mean_gaussian_noise(sys_noises)
        for hypothesis in self.hypotheses:
            for i, component in enumerate(hypothesis.bernoulli_components):
                current_system_matrix = system_matrices
                current_sys_noise = sys_noises
                current_input = inputs
                if system_matrices is not None and ndim(system_matrices) == 3:
                    current_system_matrix = system_matrices[:, :, i]
                if sys_noises is not None and ndim(sys_noises) == 3:
                    current_sys_noise = sys_noises[:, :, i]
                if inputs is not None and ndim(inputs) == 2:
                    current_input = inputs[:, i]
                component.single_target_filter.predict_linear(
                    current_system_matrix,
                    current_sys_noise,
                    current_input,
                )
                component.existence_probability *= self._get_component_probability(
                    self.tracker_param["survival_probability"], i
                )
                component.existence_probability = self._clip_probability(
                    component.existence_probability
                )
            active_birth_components = self.birth_components
            if birth_components is not None:
                active_birth_components = self._normalize_components(birth_components)
            hypothesis.bernoulli_components.extend(
                copy.deepcopy(active_birth_components)
            )
            self._assign_missing_labels(hypothesis.bernoulli_components)
        self.prune()
        self.cap()
        if self.log_prior_estimates:
            self.store_prior_estimates()

    def _enumerate_hypothesis_update_logweights(
        self,
        hypothesis,
        measurements,
        measurement_matrix,
        cov_mats_meas,
        birth_labels_by_measurement=None,
    ):
        num_measurements = measurements.shape[1]
        detection_probability = self.tracker_param["detection_probability"]
        gating_threshold = self._get_gating_distance_threshold(measurements.shape[0])
        base_log_weight = log(max(float(hypothesis.weight), 1e-300))
        results = []

        def recurse(component_index, used_measurements, log_weight, components):
            if component_index == len(hypothesis.bernoulli_components):
                posterior_components = copy.deepcopy(components)
                if self.tracker_param.get("measurement_driven_births", False):
                    for measurement_index in range(num_measurements):
                        if measurement_index in used_measurements:
                            continue
                        measurement_covariance = self._get_measurement_covariance(
                            cov_mats_meas,
                            measurement_index,
                        )
                        birth_component = self._create_birth_component_from_measurement(
                            measurements[:, measurement_index],
                            measurement_matrix,
                            measurement_covariance,
                            label=(
                                None
                                if birth_labels_by_measurement is None
                                else birth_labels_by_measurement.get(measurement_index)
                            ),
                        )
                        if birth_component is not None:
                            posterior_components.append(birth_component)
                results.append((base_log_weight + log_weight, posterior_components))
                return

            component = hypothesis.bernoulli_components[component_index]
            current_detection_probability = self._get_component_probability(
                detection_probability,
                component_index,
            )
            predicted_existence = self._clip_probability(
                component.existence_probability
            )
            missed_weight = max(
                1.0 - predicted_existence * current_detection_probability,
                1e-300,
            )
            missed_component = copy.deepcopy(component)
            missed_component.existence_probability = (
                predicted_existence * (1.0 - current_detection_probability)
            ) / missed_weight
            missed_component.existence_probability = self._clip_probability(
                missed_component.existence_probability
            )
            recurse(
                component_index + 1,
                used_measurements,
                log_weight + log(missed_weight),
                components + [missed_component],
            )
            for measurement_index in range(num_measurements):
                if measurement_index in used_measurements:
                    continue
                measurement_covariance = self._get_measurement_covariance(
                    cov_mats_meas,
                    measurement_index,
                )
                likelihood, mahalanobis_distance_squared = (
                    self._measurement_likelihood_and_distance(
                        component,
                        measurements[:, measurement_index],
                        measurement_matrix,
                        measurement_covariance,
                    )
                )
                if mahalanobis_distance_squared > gating_threshold:
                    continue
                clutter_intensity = max(
                    self._get_clutter_intensity(
                        self.tracker_param["clutter_intensity"], measurement_index
                    ),
                    1e-12,
                )
                detection_weight = (
                    predicted_existence
                    * current_detection_probability
                    * likelihood
                    / clutter_intensity
                )
                if detection_weight <= 0.0:
                    continue
                detected_component = copy.deepcopy(component)
                detected_component.single_target_filter.update_linear(
                    measurements[:, measurement_index],
                    measurement_matrix,
                    measurement_covariance,
                )
                detected_component.existence_probability = 1.0
                recurse(
                    component_index + 1,
                    used_measurements | {measurement_index},
                    log_weight + log(detection_weight),
                    components + [detected_component],
                )

        recurse(0, set(), 0.0, [])
        return results

    def update_linear(self, measurements, measurement_matrix, cov_mats_meas):
        self._ensure_numpy_backend()

        measurements = array(measurements)
        measurement_matrix = array(measurement_matrix)
        cov_mats_meas = array(cov_mats_meas)

        if measurements.ndim == 1:
            measurements = measurements.reshape(-1, 1)

        birth_labels_by_measurement = None
        if self.tracker_param.get("measurement_driven_births", False):
            birth_labels_by_measurement = {}
            for measurement_index in range(measurements.shape[1]):
                birth_labels_by_measurement[measurement_index] = self._next_label
                self._next_label += 1

        log_weighted_updates = []
        for hypothesis in self.hypotheses:
            log_weighted_updates.extend(
                self._enumerate_hypothesis_update_logweights(
                    hypothesis,
                    measurements,
                    measurement_matrix,
                    cov_mats_meas,
                    birth_labels_by_measurement=birth_labels_by_measurement,
                )
            )
        if not log_weighted_updates:
            raise ValueError("The measurement update generated no valid hypotheses.")
        normalization_constant = logsumexp(
            [log_weight for log_weight, _ in log_weighted_updates]
        )
        self._set_hypotheses(
            [
                MultiBernoulliMixtureHypothesis(
                    exp(log_weight - normalization_constant),
                    components,
                )
                for log_weight, components in log_weighted_updates
            ]
        )
        self.prune()
        self.cap()
        if self.log_posterior_estimates:
            self.store_posterior_estimates()
